### ISSUE TITLE
40303 message: Authorization requirement not met.

### ISSUE THREAD

**Issue by johnpilll** [sinch/android-flash-calling#2]
I have tried with sms verification and here is my code.

```
Config config = SinchVerification.config().applicationKey(APP_KEY).context(getApplicationContext()).build();
Verification verification = SinchVerification.createSmsVerification(config, stringPhoneNumber, listener);
verification.initiate();
```

But getting this error with **application** mode : 

```
com.sinch.verification.ServiceErrorException: Sinch backend request failed with code: 40303 message: Authorization requirement not met.
at com.sinch.verification.internal.apiservice.ApiService.extractError(ApiService.java:95)
at com.sinch.verification.internal.apiservice.ApiService.handleResponse(ApiService.java:81)
```

error with **public** mode : 

```
com.sinch.verification.ServiceErrorException: Sinch backend request failed with code: 42202 message: Invalid callback response.
at com.sinch.verification.internal.apiservice.ApiService.extractError(ApiService.java:95)
at com.sinch.verification.internal.apiservice.ApiService.handleResponse(ApiService.java:81)
```

**Comment by slavasav** [comment]
Hi,

the "APP_KEY" text here is just a placeholder, you need to replace it with the key for your application. You can get it from the dashboard after registering with Sinch.

**Comment by miceliedna** [comment]
at the place of APP_KEY , i have written my application key that is available in sinch developer dashboard

**Comment by slavasav** [comment]
Hi,

Sorry for the confusion, I can see that your app makes a request, which means that the app key is specified correctly.
When using the SDK you need to set public authorization. Also if you specify a callback url, the callback has to send "allow" response for approved verifications.

**Comment by sachinletsgo** [comment]
when I try with sandbox key it`s working fine. But when I try with production key, it show me error 40303

**Comment by slavasav** [comment]
Please make sure that your production key authorization method is also set to "public" in dashboard. If that is already the case, please contact support@sinch.com with your account details so that we could investigate further.
